spring:
  application:
    name: frontend

server:
  port: ${port:8080}

eureka:
  instance:
      hostname: ${hostname:frontend}
  client:
    registerWithEureka: true
    service-url:
      defaultZone: ${eureka:http://eureka:8761}/eureka

logging:
  level:
    com.tvelykyy: DEBUG
