spring:
  application:
    name: worker

server:
  port: ${port:8081}

eureka:
  instance:
      hostname: ${hostname:worker}
  client:
    registerWithEureka: true
    service-url:
      defaultZone: ${eureka:http://eureka:8761}/eureka

graphite:
  host: ${graphite:localhost}
  port: ${graphitePort:2003}
  amount.of.time.between.polls: 10000

logging:
  level:
    com.tvelykyy: DEBUG
