spring:
  application:
    name: eureka-server

server:
  port: ${port:8761}

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    server:
      waitTimeInMsWhenSyncEmpty: 0
  server:
    enableSelfPreservation: true
